python run.py --epoch 70 \
              --root /content/dataset_han_nom \
              --imgsz 32 \
              --task_num 128 \
              --exp 'eval' \
              --epoch_test 1 \
              --n_way 5 \
              --k_spt 1 \
              --k_qry 1 \
              --checkpoint_path /content/drive/MyDrive/Master/NLP/checkpoint/MAML_5W1S.pth \
              --test True \
              --train False